In [1]:
!pip install numpy

# **The Basics**

In [121]:
import numpy as np

a = np.array([1,2,3,4], dtype="int16")
b = np.array([[1,2,3],[3,4,5]])
c = np.array([[1,2,3],[3,4,5],[6,7,8]])
d = np.array([[[1,2,2],[2,3,5]],[[4,5,6],[8,3,9]]])

print("dim", a.ndim, b.ndim, c.ndim, d.ndim)
print("size", a.size, b.size, c.size, d.size)
print("shape", a.shape, b.shape, c.shape, d.shape)
print("data type", a.dtype)
print("item size", a.itemsize, b.itemsize, c.itemsize, d.itemsize)
print("no of bytes", a.nbytes, c.nbytes, d.nbytes)

dim 1 2 2 3
size 4 6 9 12
shape (4,) (2, 3) (3, 3) (2, 2, 3)
data type int16
item size 2 8 8 8
no of bytes 8 72 96


In [ ]:
b[[1,2],[0,1,2]]

In [ ]:
np.arange(0, 10, 2) # array([0, 2, 4, 6, 8])

In [33]:
# get a specific row
d[0,1,:]

array([2, 3, 5])

In [37]:
# getting a little more fancy
d[0,1,1:3:1]

array([3, 5])

In [40]:
# assigning values
d[0,1,1:3:1]=[1,2]
d

array([[[1, 2, 2],
        [2, 1, 2]],

       [[4, 5, 6],
        [8, 3, 9]]])

In [122]:
a[[1,2,0]]

array([2, 3, 1], dtype=int16)

### Initializing different types of arrays

In [43]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
np.ones((1,2), dtype="int32")

array([[1, 1]], dtype=int32)

In [48]:
np.full((3,3,2), 4)

array([[[4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4]]])

In [51]:
np.full_like(d, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [52]:
# random decimal numbers - make sure to not add paranthesis here
np.random.rand(4,2,3)

array([[[0.67615132, 0.03709747, 0.23362874],
        [0.38842971, 0.21979141, 0.5284847 ]],

       [[0.27074516, 0.15324233, 0.99201446],
        [0.31895412, 0.30153994, 0.8357032 ]],

       [[0.65043026, 0.67205609, 0.42200065],
        [0.64063173, 0.10425207, 0.0707442 ]],

       [[0.864509  , 0.41749998, 0.803697  ],
        [0.15769532, 0.38696488, 0.69031814]]])

In [53]:
np.random.random_sample(d.shape)

array([[[0.20619233, 0.00649217, 0.10731049],
        [0.86590146, 0.39467265, 0.82023441]],

       [[0.26163522, 0.76843844, 0.75358765],
        [0.77815569, 0.55163044, 0.10516891]]])

In [55]:
np.random.randint(4,9,size=(3,3))

array([[6, 7, 5],
       [5, 7, 6],
       [8, 5, 4]])

In [56]:
np.identity(5) # identity matrix is by nature square

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
# repeat array
d = np.array([[[1,2,2],[2,3,5]],[[4,5,6],[8,3,9]]])
r1 = np.repeat(d, 3, axis=2) # play around with axis
print(r1)

[[[1 1 1 2 2 2 2 2 2]
  [2 2 2 3 3 3 5 5 5]]

 [[4 4 4 5 5 5 6 6 6]
  [8 8 8 3 3 3 9 9 9]]]


### **QUIZ**

In [83]:
# quiz
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1
arr = np.full((5,5),9)

arr[:,0:5:4] = 1
arr[0:5:4,:] = 1

arr[1:4,1:4:2] = 0
arr[1:4:2,2] = 0

arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [85]:
# more efficient solution
arr = np.ones((5,5))
zeros = np.zeros((3,3))
zeros[1,1] = 9
arr[1:-1,1:-1] = zeros
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### **Mathematics**

In [99]:
a**2

array([1, 4, 9], dtype=int16)

In [95]:
print(c)
c.shape

[[1 2 3]
 [3 4 5]
 [6 7 8]]


(3, 3)

In [96]:
print(b)
b.shape

[[1 2 3]
 [3 4 5]]


(2, 3)

In [102]:
# b+c differet shape, failed to broadcast

In [101]:
np.cos(a)

array([ 0.5403023, -0.4161468, -0.9899925], dtype=float32)

### **Linear Algebra**

In [103]:
a = np.full((2,3), 2)
b = np.full((3,2), 3)
# a*b gives error
np.matmul(a,b)

array([[18, 18],
       [18, 18]])

In [104]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### **Statistics**

#### **What Does axis=0 Mean?**
It means:
Collapse (reduce) across the first axis (axis 0), i.e., across the blocks, and keep the result in shape of the remaining axes (2, 3).

So you’re comparing elements at the same positions across the 2 blocks and taking the minimum.

**Visually**:
```
d[0] = [[1, 2, 3],
        [4, 5, 6]]

d[1] = [[0, 3, 2],
        [7, 4, 8]]
```
Now compare element-by-element across axis 0:

```
min(d[0][0][0], d[1][0][0]) = min(1, 0) = 0
min(d[0][0][1], d[1][0][1]) = min(2, 3) = 2
min(d[0][0][2], d[1][0][2]) = min(3, 2) = 2
```
So: np.min(d, axis=0) =
[[0, 2, 2],
 [4, 4, 6]]  # shape (2, 3)

In [108]:
d

array([[[1, 2, 2],
        [2, 3, 5]],

       [[4, 5, 6],
        [8, 3, 9]]])

In [110]:
np.min(d, axis=1)

array([[1, 2, 2],
       [4, 3, 6]])

In [111]:
np.min(d, axis=2)

array([[1, 2],
       [4, 3]])

In [114]:
# rearrange
before = d
after = d.reshape(3,2,2) # will work as long as no of elements are same
after

array([[[1, 2],
        [2, 2]],

       [[3, 5],
        [4, 5]],

       [[6, 8],
        [3, 9]]])

In [117]:
# stack
v1 = [1,2,3]
v2= [5,6,7]
np.vstack((v1,v2))
np.hstack((v1,v2))

array([1, 2, 3, 5, 6, 7])

In [ ]:
# split
a = np.array([[1, 2, 3], [4, 5, 6]])
np.split(a, 3, axis=1)    # Split into 3 parts column-wise
np.hsplit(a, 3)           # Same as above
np.vsplit(a, 2)           # Row-wise split
# Output
# [array([[1, 2, 3]]), array([[4, 5, 6]])]

### **File Handling**

In [127]:
# read data
filedata = np.genfromtxt("sample_data/california_housing_test.csv", delimiter=',')
filedata

array([[         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [-1.22050e+02,  3.73700e+01,  2.70000e+01, ...,  6.06000e+02,
         6.60850e+00,  3.44700e+05],
       [-1.18300e+02,  3.42600e+01,  4.30000e+01, ...,  2.77000e+02,
         3.59900e+00,  1.76500e+05],
       ...,
       [-1.19700e+02,  3.63000e+01,  1.00000e+01, ...,  2.20000e+02,
         2.28950e+00,  6.20000e+04],
       [-1.17120e+02,  3.41000e+01,  4.00000e+01, ...,  1.40000e+01,
         3.27080e+00,  1.62500e+05],
       [-1.19630e+02,  3.44200e+01,  4.20000e+01, ...,  2.60000e+02,
         8.56080e+00,  5.00001e+05]])

In [128]:
filedata > 50

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       ...,
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ...,  True, False,  True]])

In [129]:
filedata[filedata > 50]

array([3.88500e+03, 6.61000e+02, 1.53700e+03, ..., 7.53000e+02,
       2.60000e+02, 5.00001e+05])